spring:
  profiles: fire
  application:
    name: eureka-service-register
server:
  port: 9003
eureka:
  instance:
    hostname: eureka-register-service-fire
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-register-service-wind:9001/eureka/,http://eureka-register-service-water:9002/eureka/
