---
# https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DanilKob/Microservices
          skipSslValidation: true
          force-pull: true
          searchPaths: config/{application}/{profile}/
          clone-on-start: true
          default-label: develop-config-branch
eureka:
  instance:
    preferIpAddress: true     #Register the IP of the service #rather than the server name.
  client:
    registerWithEureka: true  #Register the service with Eureka.
    fetchRegistry: true       #Pull down a local copy of the registry.
---
spring:
  profiles: dev
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/  #Location of the Eureka Service
server:
  port: 8085
---
spring:
  profiles: clustered-instance1
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/  #Location of the Eureka Service
server:
  port: 8055