eureka:
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}  # ==> This is a instance of ABC-SERVICE
  client:
    fetchRegistry: true
    registerWithEureka: true
zuul:
  routes:
    configuration-service:
      path: /configuration/**
      sensitive-headers: Set-Cookie,Authorization
    eureka-service-register:
      path: /eureka-service-register/**
      sensitive-headers: Set-Cookie,Authorization
    auth-service:
      path: /auth-service/**
      sensitive-headers: Set-Cookie,Authorization

hystrix:
  command:
    configuration-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    eureka-service-register:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    auth-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 5555