eureka:
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}  # ==> This is a instance of ABC-SERVICE
  client:
    fetchRegistry: true
    registerWithEureka: true
zuul:
  routes:
    configuration-service:
      path: /configuration/**
      sensitive-headers: Set-Cookie,Authorization
    eureka-service-register:
      path: /eureka-service-register/**
      sensitive-headers: Set-Cookie,Authorization
    auth-service:
      path: /auth-service/**
      sensitive-headers: Set-Cookie,Authorization
configuration-service:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 90000
auth-service:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 10000
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 5555