eureka:
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}  # ==> This is a instance of ABC-SERVICE
  client:
    fetchRegistry: true
    registerWithEureka: true
zuul:
  routes:
    configuration-service:
      path: /configuration/**
      sensitive-headers: Set-Cookie,Authorization
    eureka-service-register:
      path: /eureka-service-register/**
      sensitive-headers: Set-Cookie,Authorization
    auth-service:
      path: /auth-service/**
      sensitive-headers: Set-Cookie,Authorization
    booking-app:
      path: /booking/**
      sensitive-headers: Set-Cookie
configuration-service:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 90000
---
spring:
  profiles: cluster
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
server:
  port: 5555