eureka:
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}  # ==> This is a instance of ABC-SERVICE
  client:
    fetchRegistry: true
    registerWithEureka: true
zuul:
  routes:
    configuration-service:
      path: /configuration-service/**
      sensitive-headers: Set-Cookie,Authorization
    eureka-service-register:
      path: /eureka-service-register/**
      sensitive-headers: Set-Cookie,Authorization
hystrix:
    command:
      configuration-service:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds=600000
      eureka-service-register:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds=600000
---
spring:
  profiles: cluster
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
server:
  port: 5555