---
### Config client config
spring:
  cloud:
    config:
      profile: dev
### Default eureka settings for all profiles
eureka:
  instance:
    preferIpAddress: true     #Register the IP of the service #rather than the server name.
  client:
    registerWithEureka: true  #Register the service with Eureka.
    fetchRegistry: true       #Pull down a local copy of the registry.

---
spring:
  profiles: dev
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 8070
---
spring:
  profiles: clustered-instance1
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
server:
  port: 8081