spring:
  profiles: basic
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootJPAHikariCP
    password: bigbear
    platform: postgres
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/order
    username: stronguser
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        use_sql: true
    show-sql: true
logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}  # ==> This is a instance of ABC-SERVICE
  client:
    serviceUrl:
      defaultZone:  http://localhost:5555/eureka-service-register/eureka
    fetchRegistry: true
    registerWithEureka: true
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:5555/auth-service/auth/user