spring:
  profiles: wind
  application:
    name: eureka-server-register-clustered   # ==> This is Service-Id
server:
  port: 9001
eureka:
  instance:
    hostname: eureka-rigister-service-wind
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-rigister-service-water:9002/eureka/,http://eureka-rigister-service-fire:9003/eureka/
